config/routes.rb
Rails.application.routes.draw do
  devise_for :teaching_assistants
  devise_for :admins
  devise_for :students
  resources :teaching_assistants
  resources :admins
  resources :feedbacks 
  post 'feedbacks/new' => 'feedbacks#new'
  get 'admins/:id' => 'admins#show', as: 'admin_show'
  get 'teaching_assistants/:id' => 'teaching_assistants#show', as: 'ta_show'

  root 'home#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :feedbacks
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
    belongs_to :admin
    belongs_to :teaching_assistant
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/teaching_assistant.rb
class TeachingAssistant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :feedbacks
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
		@admins = Admin.all
	end
	def show
		@admin = Admin.find(params[:id])
		@feedback = @admin.feedbacks
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
	def new
		@feedback = Feedback.new
	end

	def create
		@feedback = Feedback.create(feedback_params)
		if @feedback.save
			redirect_to "/"
		end
	end

	def feedback_params
		params.require(:feedback).permit(:title, :rating, :eval, :admin_id, :teaching_assistant_id)
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/teaching_assistants_controller.rb
class TeachingAssistantsController < ApplicationController
	def index
		@teaching_assistants = TeachingAssistant.all
	end
	def show
		@ta = TeachingAssistant.find(params[:id])
		@feedback = @ta.feedbacks
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teaching_assistants_helper.rb
module TeachingAssistantsHelper
end

app/views/admins/_admin.html.erb
<td><%= link_to admin.name, admin %></td>
<td><%= link_to admin.email, admin %></td>

app/views/admins/index.html.erb
<div class="container">
  <div class="row">
    <h3>Instructors</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @admins.each do |a| %>
            <tr>
              <%= render a %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admins/show.html.erb
<% if admin_signed_in? %>
<h1>Your Evaluations</h1>
<% @feedback.each do |f| %>
    <div class="thumbnail">
        <div class="title"><%= f.title %></div>
        <div class="caption"><%= f.created_at %></div>
         <p>Rating: <%= f.rating %></p>
        <p>Evaluation: <%= f.eval %></p>
    </div>
<% end %>
<% else %>
<%= button_to "Evaluate Me", new_feedback_path(:id => @admin.id, :which_user => 'admin'), :class => "button medium" %>
<% end %>
 

app/views/feedbacks/new.html.erb
<%= simple_form_for @feedback do |p| %>
	<%= p.input :title %>
	<%= p.input :rating, collection: [6, 5, 4, 3, 2, 1]%>
	<%= p.input :eval %>
	<% if params[:which_user] == 'admin' %>
	<%= p.hidden_field :admin_id, :value => params[:id] %>
	<% else %>
	<%= p.hidden_field :teaching_assistant_id, :value => params[:id] %>
	<% end %>
	<%= p.button :submit %>	
     
<% end %>

app/views/home/index.html.erb
<h1 class="title">ONLINE EVALUATIONS BITCHES</h1>
<%= image_tag 'evaluations.jpg', id: "home-image" %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Evaluate.Me', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Dropdown
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% if student_signed_in? %>
    <li><%= link_to 'Instructors', admins_path %></li>
    <li><%= link_to 'Teaching Assistants', teaching_assistants_path %></li>
    <li><%= link_to 'Edit Your Profile',edit_student_registration_path  %></li>
    <li><%= link_to 'Log Out', destroy_student_session_path, :method=>'delete' %></li>
  <% elsif admin_signed_in? %>
   <li><%= link_to 'View Your Evaluations', admin_show_path(:id => current_admin.id) %></li>
   <li><%= link_to 'View All Your TAs', teaching_assistants_path %></li>
    <li><%= link_to 'Edit Your Profile',edit_admin_registration_path  %></li>
    <li><%= link_to 'Log Out', destroy_admin_session_path, :method=>'delete' %></li>
    <% elsif teaching_assistant_signed_in? %>
    <li><%= link_to 'View Your Evaluations', ta_show_path(:id => current_teaching_assistant.id)  %></li>
    <li><%= link_to 'Edit Your Profile',edit_teaching_assistant_registration_path  %></li>
    <li><%= link_to 'Log Out', destroy_teaching_assistant_session_path, :method=>'delete' %></li>
    <% else %>
    <li><%= link_to 'Log In As Student', new_student_session_path %></li>
    <li><%= link_to 'Log In As Admin', new_admin_session_path %></li>
    <li><%= link_to 'Log In As TA', new_teaching_assistant_session_path %></li>
    <li><%= link_to 'Join Evaluate.Me As Student', new_student_registration_path %></li>
    <li><%= link_to 'Join Evaluate.Me As TeachingAssistant', new_teaching_assistant_registration_path %></li>
    <li><%= link_to 'Join Evaluate.Me As Professor', new_admin_registration_path %></li>
  <% end %>
  </ul>
</div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if student_signed_in? %>
  <li><%= link_to 'Edit Your Profile',edit_student_registration_path  %></li>
  <li><%= link_to 'Log Out', destroy_student_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_student_session_path %></li>
  <li><%= link_to 'Join Evaluate.Me', new_student_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsdecal Proj2" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Railsdecal Proj1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/teaching_assistants/_teaching_assistant.html.erb
<td><%= link_to teaching_assistant.name, teaching_assistant %></td>
<td><%= link_to teaching_assistant.email, teaching_assistant %></td>

app/views/teaching_assistants/index.html.erb
<div class="container">
  <div class="row">
    <h3>Teaching Assistants</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @teaching_assistants.each do |t| %>
            <tr>
              <%= render t %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/teaching_assistants/show.html.erb
<% if teaching_assistant_signed_in? || admin_signed_in? %>
<h1><%= @ta.name %>'s Evaluations</h1>
<% @feedback.each do |f| %>
    <div class="thumbnail">
        <div class="title"><%= f.title %></div>
        <div class="caption"><%= f.created_at %></div>
         <p>Rating: <%= f.rating %></p>
        <p>Evaluation: <%= f.eval %></p>
    </div>
<% end %>
<% else %>
<%= button_to "Evaluate Me", new_feedback_path(:id => @ta.id, :which_user => 'teaching_assistant'), :class => "button medium" %>
<% end %>